name: Generate Snake

on:
  schedule:
    - cron: '0 */12 * * *'   # her 12 saatte bir (isteğe göre değiştir)
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write   # GITHUB_TOKEN ile çıktı branch'ine yazmak için gerekli

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake (svg + gif)
        uses: Platane/snk@v3
        with:
          github_user_name: asliaydin0
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif?color_snake=orange
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy generated files to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
